wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.12
    start_time: 1643473770
    t:
      1:
      - 12
      2:
      - 12
      3:
      - 17
      - 19
      4: 3.7.12
      5: 0.12.9
      8:
      - 5
algorithm:
  desc: null
  value: naive_string_matcher
batch_size:
  desc: null
  value: 32
freeze_processor:
  desc: null
  value: false
hidden_size:
  desc: null
  value: 4
learning_rate:
  desc: null
  value: 0.003
processor_type:
  desc: null
  value: pgn
