wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.12
    start_time: 1643925303
    t:
      1:
      - 12
      2:
      - 12
      3:
      - 17
      4: 3.7.12
      5: 0.12.10
      8:
      - 5
      10:
      - 3
